from datetime import date, datetime, timezone

from app.banking.models import (
    AccountStatus,
    AccountType,
    Address,
    BankAccount,
    BankingIssue,
    Card,
    CardStatus,
    Customer,
    IssueCategory,
    IssueSeverity,
    IssueStatus,
)

UTC = timezone.utc


def _dt(days_ago: int = 0) -> datetime:
    return datetime.now(UTC).replace(
        hour=12, minute=0, second=0, microsecond=0
    )  # stable-ish for demos


CUSTOMERS: list[Customer] = [
    Customer(
        id="cust_priya",
        full_legal_name="Priya Sharma",
        preferred_name="Priya",
        email="priya.sharma@example.com",
        phone="+91-9876543210",
        date_of_birth=date(1992, 3, 14),
        address=Address(
            line1="14 MG Road",
            line2="Apt 302",
            city="Bengaluru",
            state="KA",
            postal_code="560001",
            name_on_mail="Priya Sharma",
        ),
        customer_since=date(2018, 6, 1),
    ),
    Customer(
        id="cust_rahul",
        full_legal_name="Rahul K. Mehta",
        preferred_name="Rahul",
        email="rahul.mehta@example.com",
        phone="+91-9988776655",
        date_of_birth=date(1988, 11, 2),
        address=Address(
            line1="88 Park Street",
            city="Mumbai",
            state="MH",
            postal_code="400001",
            name_on_mail="Rahul Mehta",
        ),
        customer_since=date(2015, 2, 20),
    ),
    Customer(
        id="cust_anita",
        full_legal_name="Anita Desai",
        preferred_name="Anita",
        email="anita.desai@example.com",
        phone="+91-9123456789",
        date_of_birth=date(1995, 7, 22),
        address=Address(
            line1="22 FC Road",
            city="Pune",
            state="MH",
            postal_code="411004",
            name_on_mail="Anita Desai",
        ),
        customer_since=date(2020, 9, 10),
    ),
    Customer(
        id="cust_james",
        full_legal_name="James Chen",
        preferred_name="James",
        email="james.chen@example.com",
        phone="+91-9000012345",
        date_of_birth=date(1990, 1, 8),
        address=Address(
            line1="5 Residency Road",
            city="Hyderabad",
            state="TS",
            postal_code="500001",
            name_on_mail="James Chen",
        ),
        customer_since=date(2019, 4, 5),
    ),
    Customer(
        id="cust_sarah",
        full_legal_name="Sarah Okonkwo",
        preferred_name="Sarah",
        email="sarah.o@example.com",
        phone="+91-9111222333",
        date_of_birth=date(1985, 12, 30),
        address=Address(
            line1="10 Brigade Road",
            city="Bengaluru",
            state="KA",
            postal_code="560025",
            name_on_mail="Sarah Okonkwo",
        ),
        customer_since=date(2017, 8, 15),
    ),
]


ACCOUNTS: list[BankAccount] = [
    BankAccount(
        id="acct_priya_chk",
        account_number="100234567890",
        customer_id="cust_priya",
        account_type=AccountType.CHECKING,
        status=AccountStatus.ACTIVE,
        available_balance=84250.75,
        ledger_balance=84250.75,
        branch_code="BLR-001",
        cards=[
            Card(
                id="card_priya_1",
                last_four="4821",
                network="visa",
                status=CardStatus.ACTIVE,
                expiry_month=9,
                expiry_year=2027,
                is_primary=True,
            ),
        ],
        issues=[
            BankingIssue(
                id="iss_priya_card_risk",
                category=IssueCategory.CARD,
                severity=IssueSeverity.HIGH,
                status=IssueStatus.OPEN,
                title="Customer suspects card compromise",
                description="Unrecognized UPI hold appeared; customer wants card blocked immediately.",
                customer_visible_hint="I saw a strange charge and need to block my debit card.",
                suggested_intents=["block_card", "report_fraud", "dispute_transaction"],
                opened_at=_dt(),
                metadata={"suspicious_merchant": "QUICKPAY*TEMP", "amount_inr": 499},
            ),
        ],
    ),
    BankAccount(
        id="acct_rahul_chk",
        account_number="100345678901",
        customer_id="cust_rahul",
        account_type=AccountType.CHECKING,
        status=AccountStatus.ACTIVE,
        available_balance=156320.0,
        ledger_balance=156320.0,
        branch_code="MUM-014",
        cards=[
            Card(
                id="card_rahul_1",
                last_four="9033",
                network="mastercard",
                status=CardStatus.ACTIVE,
                expiry_month=4,
                expiry_year=2028,
            ),
        ],
        issues=[
            BankingIssue(
                id="iss_rahul_name_address",
                category=IssueCategory.ADDRESS,
                severity=IssueSeverity.MEDIUM,
                status=IssueStatus.OPEN,
                title="Legal name mismatch on mailed statements",
                description="Legal name includes middle initial 'K.' but mailers use 'Rahul Mehta' only.",
                customer_visible_hint="My name is wrong on my bank mail / address label.",
                suggested_intents=["fix_name_on_address", "update_mailing_name", "change_address"],
                opened_at=_dt(),
                metadata={
                    "legal_name": "Rahul K. Mehta",
                    "name_on_mail": "Rahul Mehta",
                },
            ),
        ],
    ),
    BankAccount(
        id="acct_anita_sav",
        account_number="200456789012",
        customer_id="cust_anita",
        account_type=AccountType.SAVINGS,
        status=AccountStatus.ACTIVE,
        available_balance=425000.5,
        ledger_balance=425000.5,
        branch_code="PUN-003",
        cards=[
            Card(
                id="card_anita_1",
                last_four="7712",
                network="rupay",
                status=CardStatus.ACTIVE,
                expiry_month=11,
                expiry_year=2026,
            ),
        ],
        issues=[
            BankingIssue(
                id="iss_anita_address_pending",
                category=IssueCategory.ADDRESS,
                severity=IssueSeverity.MEDIUM,
                status=IssueStatus.IN_PROGRESS,
                title="Address change stuck in back-office queue",
                description="Customer submitted new address; ticket open 12+ days with no update.",
                customer_visible_hint="I changed my address but it's still not updated.",
                suggested_intents=["change_address", "check_address_change_status"],
                opened_at=_dt(),
                metadata={
                    "ticket_id": "ADDR-2026-88421",
                    "requested_city": "Mumbai",
                    "days_pending": 12,
                },
            ),
        ],
    ),
    BankAccount(
        id="acct_james_chk",
        account_number="100567890123",
        customer_id="cust_james",
        account_type=AccountType.CHECKING,
        status=AccountStatus.ACTIVE,
        available_balance=28990.25,
        ledger_balance=23490.25,
        branch_code="HYD-007",
        cards=[
            Card(
                id="card_james_1",
                last_four="1156",
                network="visa",
                status=CardStatus.ACTIVE,
                expiry_month=2,
                expiry_year=2027,
            ),
        ],
        issues=[
            BankingIssue(
                id="iss_james_dup_charge",
                category=IssueCategory.TRANSACTION,
                severity=IssueSeverity.MEDIUM,
                status=IssueStatus.OPEN,
                title="Duplicate ecommerce debit",
                description="Same merchant charged twice for one order; provisional credit not applied.",
                customer_visible_hint="I was charged twice for the same purchase.",
                suggested_intents=["dispute_transaction", "request_refund"],
                opened_at=_dt(),
                metadata={
                    "merchant": "ShopNest India",
                    "amount_inr": 2499,
                    "transaction_ids": "TXN-99102,TXN-99103",
                },
            ),
        ],
    ),
    BankAccount(
        id="acct_sarah_chk",
        account_number="100678901234",
        customer_id="cust_sarah",
        account_type=AccountType.CHECKING,
        status=AccountStatus.FROZEN,
        available_balance=0.0,
        ledger_balance=51200.0,
        branch_code="BLR-002",
        cards=[
            Card(
                id="card_sarah_1",
                last_four="6609",
                network="visa",
                status=CardStatus.BLOCKED,
                expiry_month=8,
                expiry_year=2025,
            ),
        ],
        issues=[
            BankingIssue(
                id="iss_sarah_kyc",
                category=IssueCategory.KYC,
                severity=IssueSeverity.CRITICAL,
                status=IssueStatus.OPEN,
                title="KYC document expired — account restricted",
                description="PAN/Aadhaar re-verification overdue; outbound transfers blocked.",
                customer_visible_hint="My account is frozen and I can't transfer money.",
                suggested_intents=["kyc_update", "unfreeze_account", "upload_documents"],
                opened_at=_dt(),
                metadata={"kyc_due_date": "2026-09-01", "freeze_reason": "KYC_EXPIRED"},
            ),
            BankingIssue(
                id="iss_sarah_card_exp",
                category=IssueCategory.CARD,
                severity=IssueSeverity.LOW,
                status=IssueStatus.OPEN,
                title="Primary debit card expired",
                description="Replacement card not yet dispatched.",
                customer_visible_hint="My debit card expired; I need a new one.",
                suggested_intents=["order_replacement_card", "block_card"],
                opened_at=_dt(),
                metadata={"expiry": "08/2025"},
            ),
        ],
    ),
    BankAccount(
        id="acct_rahul_sav",
        account_number="200345678902",
        customer_id="cust_rahul",
        account_type=AccountType.SAVINGS,
        status=AccountStatus.ACTIVE,
        available_balance=890000.0,
        ledger_balance=890000.0,
        branch_code="MUM-014",
        cards=[],
        issues=[],
    ),
]
